# Generated by Django 2.2.6 on 2020-01-01 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criBuildingNum', models.CharField(choices=[('0', '教1'), ('1', '教2'), ('2', '教3')], max_length=10)),
                ('criRoomNum', models.CharField(max_length=10)),
                ('criStatus', models.CharField(choices=[('0', '占用'), ('1', '未占用')], max_length=5)),
            ],
            options={
                'db_table': 'ClassRoomInfo',
            },
        ),
        migrations.CreateModel(
            name='Depart',
            fields=[
                ('dNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dName', models.CharField(max_length=5, unique=True)),
                ('dSubTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dDean', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Depart',
            },
        ),
        migrations.CreateModel(
            name='DepartMajor',
            fields=[
                ('dmNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('dmName', models.CharField(max_length=20, unique=True)),
                ('dmSubTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('dmDialog', models.TextField()),
                ('dmDeam', models.CharField(max_length=20)),
                ('dmDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.Depart')),
            ],
            options={
                'db_table': 'DepartMajor',
            },
        ),
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('tNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=20)),
                ('tRank', models.CharField(choices=[('0', '助教'), ('1', '讲师'), ('2', '副教授'), ('3', '教授')], max_length=10)),
                ('tSalary', models.CharField(max_length=6)),
                ('tDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('tD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.Depart')),
                ('tDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.DepartMajor')),
            ],
            options={
                'db_table': 'Teacher',
            },
        ),
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('ciNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ciName', models.CharField(max_length=20)),
                ('ciType', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=10)),
                ('ciTerm', models.CharField(default='0', max_length=20)),
                ('ciD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.Depart')),
                ('ciDM', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.DepartMajor')),
            ],
            options={
                'db_table': 'CourseInfo',
            },
        ),
    ]
