# Generated by Django 2.2.6 on 2020-01-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yhn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfo',
            name='ciCapacity',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseinfo',
            name='ciScore',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
