# Generated by Django 2.2.6 on 2020-01-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yhn', '0001_initial'),
        ('hg', '0001_initial'),
        ('yzk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherOpenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocType', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=10)),
                ('tocCapacity', models.CharField(max_length=10, null=True)),
                ('tocCName', models.CharField(max_length=20)),
                ('tocScore', models.CharField(max_length=10)),
                ('tocStatus', models.CharField(choices=[('0', '开放'), ('1', '待审核')], max_length=10)),
                ('tocOpenTime', models.CharField(max_length=100, null=True)),
                ('tocTerm', models.CharField(max_length=100, null=True)),
                ('tocTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.TeacherInfo')),
            ],
            options={
                'db_table': 'TeacherOpenCourse',
            },
        ),
        migrations.CreateModel(
            name='StudentsChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cType', models.CharField(choices=[('0', 'A'), ('1', 'B'), ('2', 'C'), ('3', 'D')], max_length=10)),
                ('cGrade', models.CharField(blank=True, max_length=10, null=True)),
                ('cStatus', models.CharField(choices=[('0', '重修'), ('1', '通过'), ('2', '退选'), ('3', '未选'), ('4', '默认')], max_length=10)),
                ('cCNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzk.Course')),
                ('cStuNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hg.Student')),
                ('cTeacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yhn.TeacherInfo')),
            ],
            options={
                'db_table': 'StudentsChoice',
            },
        ),
    ]
