# Generated by Django 2.2.6 on 2020-01-01 13:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginInfo',
            fields=[
                ('lNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('lIden', models.CharField(choices=[('0', '学生'), ('1', '教师'), ('2', '教务'), ('3', 'root')], max_length=10)),
                ('lPwd', models.CharField(default='000000', max_length=10)),
            ],
            options={
                'db_table': 'LoginInfo',
            },
        ),
        migrations.CreateModel(
            name='OperateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=50)),
                ('iden', models.CharField(choices=[('0', '学生'), ('1', '教师'), ('2', '教务'), ('3', 'root')], max_length=10)),
                ('dowhat', models.CharField(choices=[('0', '增加了'), ('1', '删除了'), ('2', '查找了'), ('3', '修改了'), ('4', '登陆了')], max_length=50)),
                ('detail', models.CharField(blank=True, max_length=100, null=True)),
                ('review_status', models.CharField(choices=[('0', '默认'), ('1', '通过'), ('2', '未通过')], max_length=10)),
                ('submit_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'OperateLog',
            },
        ),
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.CharField(max_length=50)),
                ('login_iden', models.CharField(choices=[('0', '学生'), ('1', '教师'), ('2', '教务'), ('3', 'root')], max_length=10)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('loginer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lh.LoginInfo')),
            ],
            options={
                'db_table': 'LoginLog',
            },
        ),
    ]
