# Generated by Django 2.2.6 on 2020-01-01 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yzk', '0002_auto_20200101_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseinfolist',
            name='cNo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yzk.Course'),
        ),
    ]
