# Generated by Django 2.2.6 on 2020-01-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzk', '0003_auto_20200101_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfolist',
            name='cStatus',
            field=models.CharField(choices=[('0', '重修'), ('1', '通过'), ('2', '退选'), ('3', '未选'), ('4', '默认')], max_length=10, null=True),
        ),
    ]
