# Generated by Django 2.2.6 on 2020-01-02 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yzk', '0004_courseinfolist_cstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinfolist',
            name='cGrade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='courseinfolist',
            name='cPercent',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
